version: '3.8'
services:
  # 1. บริการ Nginx (เว็บเซิร์ฟเวอร์)
  nginx:
    image: nginx:alpine
    container_name: command-nginx
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks: # <--- เพิ่มส่วนนี้
      - shared-network

  # 2. บริการ PHP
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: command-php
    environment: # <-- เพิ่มส่วนนี้
      - TZ=Asia/Bangkok
    volumes:
      - ./src:/var/www/html
    networks: # <--- เพิ่มส่วนนี้
      - shared-network

  # 3. บริการ MySQL (ฐานข้อมูล)
  db:
    image: mysql:8.0
    container_name: command-db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      TZ: Asia/Bangkok # <-- เพิ่มสำหรับ MySQL
    volumes:
      - db_data:/var/lib/mysql
    networks: # <--- เพิ่มส่วนนี้
      - shared-network
    command:
      - --default-authentication-plugin=mysql_native_password
      - --wait_timeout=31536000
      - --interactive_timeout=31536000
      - --default-time-zone=+07:00 # <-- เพิ่มบรรทัดนี้

volumes:
  db_data:

# ประกาศใช้งาน Network จากภายนอก
networks: # <--- เพิ่มส่วนนี้เข้ามาล่างสุด
  shared-network:
    external: true