services:
  # 1. บริการ Nginx (เว็บเซิร์ฟเวอร์)
  nginx:
    image: nginx:alpine
    container_name: command-nginx
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks: # <--- เพิ่มส่วนนี้
      - shared-network

  # 2. บริการ PHP
  php:
    build:
      context: ./docker/php
    container_name: command-php
    volumes:
      - ./src:/var/www/html
    networks: # <--- เพิ่มส่วนนี้
      - shared-network

  # 3. บริการ MySQL (ฐานข้อมูล)
  db:
    image: mysql:8.0
    container_name: command-db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: command_db
      MYSQL_USER: command
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    networks: # <--- เพิ่มส่วนนี้
      - shared-network

volumes:
  db_data:

# ประกาศใช้งาน Network จากภายนอก
networks: # <--- เพิ่มส่วนนี้เข้ามาล่างสุด
  shared-network:
    external: true